USE [master]
GO

/****** Object:  Database [brato]    Script Date: 11/24/2012 13:23:11 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'brato')
DROP DATABASE [brato]
GO

USE [master]
GO

/****** Object:  Database [brato]    Script Date: 11/24/2012 13:23:11 ******/
CREATE DATABASE [brato] ON  PRIMARY 
( NAME = N'brato', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\brato.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'brato_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\brato_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [brato] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [brato].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [brato] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [brato] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [brato] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [brato] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [brato] SET ARITHABORT OFF 
GO

ALTER DATABASE [brato] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [brato] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [brato] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [brato] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [brato] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [brato] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [brato] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [brato] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [brato] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [brato] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [brato] SET  DISABLE_BROKER 
GO

ALTER DATABASE [brato] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [brato] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [brato] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [brato] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [brato] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [brato] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [brato] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [brato] SET  READ_WRITE 
GO

ALTER DATABASE [brato] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [brato] SET  MULTI_USER 
GO

ALTER DATABASE [brato] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [brato] SET DB_CHAINING OFF 
GO

